### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by whsecurity** [Beaten-Sect0r/yii2-core#1]
I receive a 404 error after the installation
![screen shot 2016-05-22 at 13 22 16](https://cloud.githubusercontent.com/assets/1336134/15453478/3f977252-2020-11e6-90ad-26c8401b21d7.png)
Any Ideas?

**Comment by Beaten-Sect0r** [comment]
Single domain installation?
Remove 'baseUrl' => '' from frontend/config/main.php

**Comment by whsecurity** [comment]
Thanks for that!
Now I'm ok with the frontend but the /admin doesn't work... I tried to remove the 'baseUrl' => '/admin' but it didn't make the trick...

**Comment by Beaten-Sect0r** [comment]
What shows?

**Comment by whsecurity** [comment]
The frontend..
Also the storage doesn't seems to work properly. It saves the image but it didn't show it in the user profile
My MAMP installation is under localhost:<ip>, inside there is with symlink a core file, which has the yii2-core, yii2 etc installation
I hope this helps

**Comment by Beaten-Sect0r** [comment]
.env
```
# Urls
# ----
FRONTEND_URL = //folder-name/frontend/web
BACKEND_URL = //folder-name/backend/web
STORAGE_URL = //folder-name/storage
```

**Comment by whsecurity** [comment]
Now at core/backend/web I see that
![screen shot 2016-05-22 at 15 39 29](https://cloud.githubusercontent.com/assets/1336134/15453991/7cec1df2-2033-11e6-82a0-9d2f76b9180b.png)

**Comment by whsecurity** [comment]
I find it!
I remove from main.php at backend->config the 'baseUrl' => '/admin'
I'm trying to fix the storage now

**Comment by whsecurity** [comment]
If you have any ideas..? I'm trying to fix the storage but I didn't have any success. I tried with different settings to htaccess, main.php and env. Probably I didn't find the right ones...

**Comment by Beaten-Sect0r** [comment]
# Try again:

### Get source code via Composer

You can install this application template with `composer` using the following command:

```
composer create-project --prefer-dist --stability=dev Beaten-Sect0r/yii2-core
```


### Setup application

1. Copy `.env.dist` to `.env` in the project root.

2. Adjust settings in `.env` file
    - Set debug mode and your current environment

    ```
    YII_DEBUG = true
    YII_ENV = dev
    ```

    - Set DB configuration

    ```
    DB_DSN = mysql:host=localhost;port=3306;dbname=yii2-core
    DB_USERNAME = user
    DB_PASSWORD = password
    ```

    - Set application canonical urls

    ```
    FRONTEND_URL = http://yii2-core.dev
    BACKEND_URL = http://backend.yii2-core.dev
    STORAGE_URL = http://storage.yii2-core.dev
    ```

3. Run in command line

```
php yii app/setup
```

### Authentication

`administrator` role account

```
Login: Administrator
Password: passwd
```

### Configure your web server

Or configure your web server with three different web roots:
- yii2-core.dev => /path/to/yii2-core/frontend/web
- backend.yii2-core.dev => /path/to/yii2-core/backend/web
- storage.yii2-core.dev => /path/to/yii2-core/storage

**Comment by Beaten-Sect0r** [comment]
If not work then send the archive to beatensect0r [@] gmail.com

**Comment by Beaten-Sect0r** [comment]
https://www.youtube.com/watch?v=XAC5joagA70
