### ISSUE TITLE
Disable bootstrap asset in frontend

### ISSUE THREAD

**Issue by ghost** [Beaten-Sect0r/yii2-core#11]
How can I possibly disable bootstrap assets like css js etc. in frontend only. I already tried removing 'yii\bootstrap\BootstrapAsset' in frontend AppAsset.php but still generating bootstrap assets in the frontend web assets folder

**Comment by Beaten-Sect0r** [comment]
Hi,
http://stackoverflow.com/a/26734892
https://github.com/Beaten-Sect0r/yii2-core/blob/master/frontend/config/main.php#L21

**Comment by ghost** [comment]
I did that. Even remove everything from frontend AppAsset
![error](https://cloud.githubusercontent.com/assets/5134552/24071444/b7179e6e-0c0c-11e7-9b4d-9b3a36c926d1.PNG)

**Comment by Beaten-Sect0r** [comment]
Then you need to drop all bootstrap widgets.
https://github.com/Beaten-Sect0r/yii2-core/blob/master/frontend/views/layouts/main.php#L31
https://github.com/Beaten-Sect0r/yii2-core/blob/master/frontend/views/layouts/main.php#L69
https://github.com/Beaten-Sect0r/yii2-core/blob/master/frontend/views/layouts/main.php#L76
https://github.com/Beaten-Sect0r/yii2-core/blob/master/frontend/views/layouts/main.php#L79
https://github.com/Beaten-Sect0r/yii2-core/blob/master/frontend/views/article/_categoryItem.php#L10
