### ISSUE TITLE
Question: Redactor widget vova07\imperavi

### ISSUE THREAD

**Issue by ghost** [Beaten-Sect0r/yii2-core#12]
I am trying to allow photo and video only. I was able to hide formatting buttons by this
`'buttonsHide'=> ['bold','formatting','italic','deleted','outdent','indent','link','alignment','horizontalrule','html','unorderedlist','orderedlist'],`

but now I want to disable text input from the user. any insights?

**Comment by Beaten-Sect0r** [comment]
Disable the editor. To add to the database table of photos and videos.
Or use a regular expression.
