### ISSUE TITLE
directory is not writable by web process

### ISSUE THREAD

**Issue by ghost** [Beaten-Sect0r/yii2-core#13]
```
The directory is not writable by the Web process: frontend/web/assets
Warning: mkdir(): Permission denied in vendor/yiisoft/yii2/helpers/BaseFileHelper.php on line 488
```

I already give permission to apache and even tried chmod 0777 to runtime, web/assets and frontend/assets folder

**Comment by Beaten-Sect0r** [comment]
`sudo chown -R www-data:www-data /path/to/yii2-core`

**Comment by ghost** [comment]
already did that. still doesnt work. same error with warning 
Warning: mkdir(): Permission denied in vendor/yiisoft/yii2/helpers/BaseFileHelper.php on line 488

by the way, im doing this with centos 7

**Comment by ghost** [comment]
I was able to solve it. SELinux is blocking httpd from writing/creating dirs
chcon -R -t httpd_sys_content_t /path/to/www
chcon -R -t httpd_sys_content_rw_t /path/to/www/dir/for/rw
