### ISSUE TITLE
InvalidParamException' with message 'Invalid path alias: @frontendUrl'

### ISSUE THREAD

**Issue by cobabikin** [Beaten-Sect0r/yii2-core#16]
`
Fatal error: Uncaught exception 'yii\base\InvalidParamException' with message 'Invalid path alias: @frontendUrl' in C:\xampp\htdocs\informasi\vendor\yiisoft\yii2\BaseYii.php:154 Stack trace: #0 C:\xampp\htdocs\informasi\frontend\config\main.php(10): yii\BaseYii::getAlias('@frontendUrl') #1 C:\xampp\htdocs\informasi\frontend\web\index.php(22): require('C:\\xampp\\htdocs...') #2 {main} thrown in C:\xampp\htdocs\informasi\vendor\yiisoft\yii2\BaseYii.php on line 154
`

**Comment by Beaten-Sect0r** [comment]
show me /common/config/bootstrap.php

**Comment by cobabikin** [comment]
```php
<?php

/**
 * Setting path aliases
 */
Yii::setAlias('root', realpath(__DIR__ . '/../../'));
Yii::setAlias('common', realpath(__DIR__ . '/../../common'));
Yii::setAlias('frontend', realpath(__DIR__ . '/../../frontend'));
Yii::setAlias('backend', realpath(__DIR__ . '/../../backend'));
Yii::setAlias('console', realpath(__DIR__ . '/../../console'));
Yii::setAlias('storage', realpath(__DIR__ . '/../../storage'));

/**
 * Setting url aliases
 */
Yii::setAlias('frontendUrl', env('FRONTEND_URL'));
Yii::setAlias('backendUrl', env('BACKEND_URL'));
Yii::setAlias('storageUrl', env('STORAGE_URL'));
Yii::setAlias('frontendWebroot', '');
```

**Comment by Beaten-Sect0r** [comment]
https://github.com/Beaten-Sect0r/yii2-core/blob/master/frontend/web/index.php#L16
