### ISSUE TITLE
shared hosting .. cannot load image from storage folder..but localhost work

### ISSUE THREAD

**Issue by cobabikin** [Beaten-Sect0r/yii2-core#17]
shared hosting
![my site](https://user-images.githubusercontent.com/17420664/31354323-8d83b35a-ad68-11e7-943c-6c40f31b52fb.PNG)

localhost 
![mylocal](https://user-images.githubusercontent.com/17420664/31354344-a8276eae-ad68-11e7-831c-1ff463380176.PNG)

this my htaccess
```
# Set the default charset.
AddDefaultCharset UTF-8

# Don't show directory listings for URLs which map to a directory.
Options -Indexes

# Enable symlinks
Options +FollowSymlinks

# Enable mod_rewrite
RewriteEngine On

# Backend redirect
RewriteCond %{REQUEST_URI} ^/backend
RewriteRule ^backend/(.*)$ backend/web/$1 [L]

# Storage redirect
RewriteCond %{REQUEST_URI} ^/storage
RewriteRule ^storage/(.*)$ storage/$1 [L]

# Frontend redirect
RewriteCond %{REQUEST_URI} ^(.*)$
RewriteRule ^(.*)$ frontend/web/$1
```

Cpanel 

![panel](https://user-images.githubusercontent.com/17420664/31354549-5a37fcd0-ad69-11e7-80fe-94003a37ca88.PNG)

sorry my english is bad

**Comment by Beaten-Sect0r** [comment]
The file exists on the server?
Change chmod to 777 the storage directory.

**Comment by cobabikin** [comment]
my file exist on the server and permission file 777 ...but not work
"storage
![st](https://user-images.githubusercontent.com/17420664/31399607-78ae4a1e-ae1f-11e7-9212-d7a1762722e4.PNG)
"avatars"
![ava](https://user-images.githubusercontent.com/17420664/31399603-778b811a-ae1f-11e7-917e-9f87a7b367be.PNG)
"file"
![ff](https://user-images.githubusercontent.com/17420664/31399605-78218db8-ae1f-11e7-8fe4-134c2d3587f0.PNG)

**Comment by cobabikin** [comment]
and log error from cpanel

" /public_html/storage/.htaccess: Invalid command 'php_flag', perhaps misspelled or defined by a module not included in the server configuration, referer: http://mysite..../backend

**Comment by Beaten-Sect0r** [comment]
remove /public_html/storage/.htaccess
or
```
# Disable php engine.
#php_flag engine off

# Don't show directory listings for URLs which map to a directory.
Options -Indexes
```

**Comment by cobabikin** [comment]
SOLVED .. thanks for the help
