### ISSUE TITLE
yii2-notification-wrapper

### ISSUE THREAD

**Issue by loveorigami** [Beaten-Sect0r/yii2-core#2]
Делал для своего проекта вывод флеш сообщений, вида
https://github.com/Beaten-Sect0r/yii2-core/blob/master/frontend/modules/account/controllers/SignInController.php#L106

разными js библиотеками. Чтоб можно было их сменить легко на фронтенде, сделал небольшой модуль
https://github.com/loveorigami/yii2-notification-wrapper

Могу порекомендовать его использовать вместо
https://github.com/Beaten-Sect0r/yii2-core/blob/master/frontend/views/layouts/main.php#L79

**Comment by Beaten-Sect0r** [comment]
Спасибо, вскоре пожалуй так и сделаю.

**Comment by Beaten-Sect0r** [comment]
https://github.com/Beaten-Sect0r/yii2-core/commit/d7eb411ae383e1a7756634ab6559f89ba6320f92
