### ISSUE TITLE
"Registration is disabled" bug

### ISSUE THREAD

**Issue by moggiex** [Beaten-Sect0r/yii2-core#20]
Howdy,

In the administration `site/settings` set Registration to disabled, then sign out.

Go to the front end and go to `account/sign-in/login`

The "Signup" button is still available, thus can be clicked on, the user is transferred to blank page (route) `account/sign-in/signup.` 

Click backwards and then you get the message "Registration is disabled."

Would it not be better just to hide the "Signup" button in the first place if registration is disabled?

Matt

**Comment by Beaten-Sect0r** [comment]
thnx
