### ISSUE TITLE
SUGGESTION : please update to yii2 2.0.15 due to security issue

### ISSUE THREAD

**Issue by sinfuljosh** [Beaten-Sect0r/yii2-core#21]
you can read about it in the below link, but there was sql injection possibilities that could compromise peoples sites.

one big change is findone and findall  are limited to AR properties,

acording to their post, since you are using 2.0.14 it should be an easy upgrade to 2.0.15

https://www.yiiframework.com/news/168/releasing-yii-2-0-15-and-database-extensions-with-security-fixes#summary-of-affected-classes-methods-and-composer-packages

https://www.yiiframework.com/forum/index.php/topic/76661-releasing-yii-2015-and-database-extensions-with-security-fixes/

**Comment by sinfuljosh** [comment]
Nevermind, since just realized you are using dev-master of yii2.

**Comment by Beaten-Sect0r** [comment]
https://github.com/Beaten-Sect0r/yii2-core/commit/b6d61c95c345d14f37d5daeb1b5baaf8ec4ce01a
