### ISSUE TITLE
How to install vagrant?

### ISSUE THREAD

**Issue by varrek1** [Beaten-Sect0r/yii2-core#3]
What is needed for a package yii2-core?

**Comment by Beaten-Sect0r** [comment]
https://github.com/Beaten-Sect0r/yii2-core/commit/17555117e8894661fa45727d88202e9a6aaf2cb2
https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/start-installation.md#installing-using-vagrant

**Comment by varrek1** [comment]
Это yii-advanced ,а как установить yii2-core?

**Comment by varrek1** [comment]
Thank you very much!!!:)

**Comment by Beaten-Sect0r** [comment]
Я дал ссылку на инструкцию для yii2-app-advanced, по тому что ещё не успел добавить в документацию, а процесс установки идентичен.

**Comment by varrek1** [comment]
Вы же только что выложили поддержку вагранта))я уже установил ,но у вас ошибка в синтаксисе mysql . В файле once-as-root.sh.Из-за этого возникает 502 ошибка.Исправил ,но ошибка не изчезает...

**Comment by Beaten-Sect0r** [comment]
Можно поконкретней где ошибка?
Буду сейчас разбираться, раньше с vagrant не имел дело.

**Comment by varrek1** [comment]
once-as-root.sh 65 строка.Создание бд. Имя бд нельзя через тире.Сделал другое имя осталась 502.Сделал php yii migrate.Выпадает ошибка:segmentation fault core dumped

**Comment by varrek1** [comment]
Немного не по теме ,но например у Laravel есть такая утилита Homestead,и если кто-нибудь реализует нечто подобное для yii ,я думаю будет очень много благодарных людей...

**Comment by Beaten-Sect0r** [comment]
Отпишите пожалуйста, когда проверите.

**Comment by varrek1** [comment]
Все отлично!Спасибо большое

**Comment by Beaten-Sect0r** [comment]
Будут ещё какие-то идеи - пишите.
