### ISSUE TITLE
Assets were not found after installation

### ISSUE THREAD

**Issue by ghost** [Beaten-Sect0r/yii2-core#5]
![capture](https://cloud.githubusercontent.com/assets/5134552/17098079/1d47141e-5293-11e6-9098-0f2ab210aa50.JPG)

**Comment by ghost** [comment]
fixes my issue after putting this code on backend > config > main.php
`'baseUrl' => '/foliedotph/backend/web',`

take note the I am running this on localhost using xampp

**Comment by Beaten-Sect0r** [comment]
https://github.com/Beaten-Sect0r/yii2-core/blob/master/docs/installation.md#configure-your-web-server

https://www.youtube.com/watch?v=XAC5joagA70

**Comment by ghost** [comment]
now it works. but when I try to upload pictures for users or a static page, it can't retrieve the photo. But I can see the photo inside the said directory.

![untitled2](https://cloud.githubusercontent.com/assets/5134552/17277774/0af699f2-577e-11e6-833e-f250ab28f5c6.png)

**Comment by Beaten-Sect0r** [comment]
chmod?
Show me .env

**Comment by ghost** [comment]
![capture](https://cloud.githubusercontent.com/assets/5134552/17278003/5bf4b212-5783-11e6-9708-a13efc2585bc.JPG)

```
YII_DEBUG = true
YII_ENV = dev
FRONTEND_URL = http://folie.ph
BACKEND_URL = http://backend.folie.ph
STORAGE_URL = http://storage.folie.ph
```

**Comment by Beaten-Sect0r** [comment]
Show httpd-vhosts.conf and /etc/hosts

**Comment by Beaten-Sect0r** [comment]
https://github.com/Beaten-Sect0r/yii2-core/blob/master/docs/installation.md#single-domain-installation

**Comment by ghost** [comment]
```
<VirtualHost *:80>
    DocumentRoot "D:/Programs/xampp/htdocs/foliedotph/frontend/web"
    ServerName folie.ph
</VirtualHost>

<VirtualHost *:80>
    DocumentRoot "D:/Programs/xampp/htdocs/foliedotph/backend/web"
    ServerName backend.folie.ph
</VirtualHost>

<VirtualHost *:80>
    DocumentRoot "D:/Programs/xampp/htdocs/foliedotph/storage"
    ServerName storage.folie.ph
    ErrorLog "logs/storage.folie.ph-error.log"
    CustomLog "logs/storage.folie.ph-access.log" common
</VirtualHost>
```

```
127.0.0.1 folie.ph
127.0.0.1 backend.folie.ph
127.0.0.1 storage.folie.ph
```

**Comment by Beaten-Sect0r** [comment]
Should work.
Use vagrant https://github.com/Beaten-Sect0r/yii2-core/blob/master/docs/installation.md#vagrant-installation
or try another wamp.

**Comment by ghost** [comment]
I was able to work it out but change this on my backend config

```
'request' => [
            'baseUrl' => '',
```

and have this on .env

```
FRONTEND_URL = http://folie.ph
BACKEND_URL = http://backend.folie.ph
STORAGE_URL = http://storage.folie.ph
```

**Comment by Beaten-Sect0r** [comment]
`'baseUrl' => '/',` - you need to remove.

**Comment by mitramichaeljade** [comment]
It was able to locate web shell, file manager, db manager etc but not gii
![capture](https://cloud.githubusercontent.com/assets/5134552/17390624/5e142378-5a41-11e6-8860-f39438a66d9a.JPG)
