### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [Beaten-Sect0r/yii2-core#6]
How does article.created_at and article.update_at id get the current time  in table ARTICLES table

**Comment by Beaten-Sect0r** [comment]
Hi!
https://github.com/Beaten-Sect0r/yii2-core/blob/master/frontend/controllers/ArticleController.php#L52
https://github.com/Beaten-Sect0r/yii2-core/blob/master/frontend/views/article/_item.php#L22
example:
```php
<?php
use common\models\Article;

$id = 1;
$model = Article::find()->where(['id' => $id])->one();
echo $model->published_at;
echo $model->created_at;
echo $model->updated_at;
?>
```

**Comment by mitramichaeljade** [comment]
I mean, how it was able to get/generate the current time and inserted into the database?

**Comment by Beaten-Sect0r** [comment]
Select your [timezone](https://github.com/Beaten-Sect0r/yii2-core/blob/master/.env.dist#L21)
http://php.net/manual/en/timezones.php

http://www.yiiframework.com/doc-2.0/yii-i18n-formatter.html#$defaultTimeZone-detail
http://www.yiiframework.com/doc-2.0/yii-behaviors-timestampbehavior.html
