### ISSUE TITLE
IPv6 validation can not be used. PHP is compiled without IPv6

### ISSUE THREAD

**Issue by parich** [Beaten-Sect0r/yii2-core#8]
login

Invalid Configuration – yii\base\InvalidConfigException
IPv6 validation can not be used. PHP is compiled without IPv6

**Comment by Beaten-Sect0r** [comment]
comment out a line
https://github.com/Beaten-Sect0r/yii2-core/blob/master/frontend/modules/account/controllers/SignInController.php#L69
